spring:
  profiles:
    active: ${profile:dev}
    include: dbinfo
  application:
    name: plf
  datasource:
    platform: mysql
    hikari:
      auto-commit: true
      connection-test-query: 'SELECT 1'
      maximum-pool-size: 100

server:
  port: 8090
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30

# mybatis mapper 扫描位置
mybatis:
  mapperLocations: classpath:repository/**/*Repository*.xml

